### ISSUE TITLE
Rich Text messes up the view

### ISSUE THREAD

**Issue by pjarnfelt** [radiatoryang/merino#15]
Having textmesh pro rich text messes up the text box in Merino:
![rich_text](https://user-images.githubusercontent.com/891674/45755804-a00cc680-bc1f-11e8-8f59-eba60fb0b16c.PNG)

text to reproduce: Sally: <size=60%>Hello I am 60% smaller</size> than the rest

**Comment by radiatoryang** [comment]
whoops... yeah, the code overlay uses rich text to colorize all the syntax highlighting!

I think the solution will involve invisibly isolating user-input angle brackets somehow, so that they don't get interpreted within the editor

unfortunately there's nothing like a <code> isolation tag in Unity rich text, so I might have to invent kludge my own hack here, we'll see

**Comment by radiatoryang** [comment]
finally got around to fixing this, will do a v0.41 release after finishing a few more things in a few days

![image](https://user-images.githubusercontent.com/2285943/46301415-4a67e080-c574-11e8-923a-4016eb2e6f23.png)
