### ISSUE TITLE
Merino is saving files with line endings that are incompatible with Yarn Editor

### ISSUE THREAD

**Issue by swakdaddy** [radiatoryang/merino#26]
It is converting every line ending to CR LF which causes the Yarn Editor to not draw lines between nodes. It needs LF only to function correctly.

**Comment by radiatoryang** [comment]
Looked into this further. I think the culprit is here: https://github.com/radiatoryang/merino/blob/7519f92b1775497bb3e01854d47af56ab5971234/Assets/Merino/Editor/Scripts/YarnSpinnerConsole/YarnSpinnerFileFormatConverter.cs#L201-L209

Problem: ``StringBuilder.AppendLine()`` uses ``Environment.NewLine`` for line endings, which is a hard-coded constant equal to ``"\r\n"`` as a relic from Windows .NET convention. More info: https://stackoverflow.com/questions/14735292/when-i-use-stringbuilder-append-instead-of-appendline-do-i-need-to-add-additio

Proposed solution: Because we cannot modify the constant ``Environment.NewLine``, we should switch to regular ``StringBuilder.Append()`` and manually apply our own line endings. However, some users might prefer "\r\n" for whatever reason, and most IDEs let users specify what type of line ending to use, so we should follow that pattern and let users set a preferred line ending format in the Merino Editor Preferences. By default, maybe it should be set initially to "\n" to preserve compatibility with Yarn Editor.

I'll probably get around to this in ~2 weeks after GDC, but anyone is welcome to submit a PR or make the necessary edits.
