### ISSUE TITLE
See Invisible Characters

### ISSUE THREAD

**Issue by LivKanyway** [radiatoryang/merino#29]
Unfortunately I've found that one misplaced space can mess up multiple options when presenting shortcut options (->). Merino should have the ability to show invisible characters much like other text editors.

**Comment by radiatoryang** [comment]
I think this is possible. It would involve doing a string.Replace() but only on the highlight overlay text, in the main Merino EditorWindow class. It might break wordwrapping though based on the characters used to render whitespace, which will also break line numbers and a bunch of other stuff, so some testing will be needed.

Honestly I won't be able to get around to this until maybe late July.

**Comment by radiatoryang** [comment]
hello, I tried adding this but unfortunately it definitely does break wordwrapping and there's no real way for me to fix this in Unity Editor IMGUI, unless anyone knows of some secret standard Unicode character that functions like a space in IMGUI but isn't invisible?

![image](https://user-images.githubusercontent.com/2285943/60916304-0076fe00-a25c-11e9-9f3c-ee3d318cc325.png)

but hopefully this isn't so necessary anymore in your particular use case, since issue #23 got newly fixed for v0.5.4, and now spaces within the ``->`` shortcut option syntax should be much more visible?

I'm happy to re-open and re-examine this issue if you have some other need or use case for displaying invisible characters, but for now, I'm going to close it
